  pwnenv:
    build:
      context: .
      dockerfile: heap.Dockerfile
    pid: "service:<service-name>"
    cap_add:
      - "SYS_PTRACE"
    depends_on:
      - "<service-name>"
    stdin_open: true
    tty: true
